apps/blog/urls.py
# coding=utf-8
from django.conf.urls import patterns, url
from django.views.generic import TemplateView, DetailView
from apps.blog.models import Post
from .views import PostListView, PostDetailView, PostSectionDetailView
from .ajax import load_more_posts, postcomment_add

__author__ = 'alexy'


urlpatterns = patterns(
    'apps.blog.views',
    url(r'^$', PostListView.as_view(), name='list'),
    # url(r'^post/$', TemplateView.as_view(template_name='blog/post_detail.html'), name='detail'),
    url(r'^(?P<slug>[\w-]+)$', PostDetailView.as_view(), name='detail'),
    url(r'^(?P<slug>[\w-]+)/txt/$', DetailView.as_view(
        model=Post,
        template_name='blog/post_detail_mail.html'),
        name='detail-txt'
        ),
    url(r'^section/(?P<slug>[\w-]+)$', PostSectionDetailView.as_view(), name='section'),
    url(r'^ajax-load/$', load_more_posts, name='load-more'),
    url(r'^ajax-comment/$', postcomment_add, name='postcomment-add'),
)

apps/landing/urls.py
# coding=utf-8
from django.conf.urls import patterns, url
from django.views.generic import TemplateView

from .views import LandingView, MailView

__author__ = 'alexy'


urlpatterns = patterns(
    '',
    url(r'^$', LandingView.as_view(), name='index'),
    url(r'^thnx/$', TemplateView.as_view(template_name='landing/ok.html'), name='thnx'),
    url(r'^mail/$', MailView.as_view(), name='mail'),
)

apps/ticket/urls.py
# coding=utf-8
from django.conf.urls import patterns, url

from .views import ticket_send, mail_read, ticket_csv

__author__ = 'alexy'


urlpatterns = patterns(
    '',
    url(r'^$', ticket_send, name='send'),
    url(r'^csv/$', ticket_csv, name='csv'),
    url(r'^check.png/(?P<pk>\d+)/$', mail_read, name='mail_read'),
)

cms/urls.py
# coding=utf-8
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.generic import TemplateView

urlpatterns = patterns(
    '',

    url(r'^ckeditor/', include('ckeditor.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('core.urls')),
    url(r'', include('apps.landing.urls', namespace='landing')),
    # url(r'blog/', include('apps.blog.urls', namespace='blog')),
    url(r'ticket/', include('apps.ticket.urls', namespace='ticket')),
    url(r'sender/', include('apps.sender.urls', namespace='sender')),
)

if settings.DEBUG:
    # import debug_toolbar
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += staticfiles_urlpatterns()
    # urlpatterns += patterns(
    #     '',
    #     url(r'^__debug__/', include(debug_toolbar.urls)),
    # )

apps/blog/models.py
# coding=utf-8
from PIL import Image
from django.core.urlresolvers import reverse
from django.db import models
from ckeditor.fields import RichTextField
from core.files import upload_to
from core.base_model import CommonPage, Common

__author__ = 'alexy'


class BlogSetup(models.Model):
    class Meta:
        verbose_name = u'Настройки блога'
        verbose_name_plural = u'Настройки блога'
        app_label = 'blog'

    def __unicode__(self):
        return self.meta_title

    meta_title = models.CharField(max_length=256, verbose_name=u'META заголовок')
    meta_key = models.CharField(max_length=256, blank=True, null=True, verbose_name=u'META ключевые слова')
    meta_desc = models.CharField(max_length=256, blank=True, null=True, verbose_name=u'META описание')


class PostSection(CommonPage):
    class Meta:
        verbose_name = u'Категория'
        verbose_name_plural = u'Категории'
        app_label = 'blog'
        ordering = ('sort',)

    def __unicode__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:section', args=(self.slug,))

    slug = models.SlugField(
        max_length=100,
        verbose_name=u'url'
    )
    sort = models.PositiveIntegerField(default=1, verbose_name=u'Сортировка')


class Post(CommonPage):
    class Meta:
        verbose_name = u'Статья'
        verbose_name_plural = u'Статьи'
        app_label = 'blog'
        ordering = ('sort',)

    def get_absolute_url(self):
        return reverse('blog:detail', args=(self.slug,))

    def save(self, *args, **kwargs):
        super(Post, self).save()
        if self.image:
            image = Image.open(self.image)
            (width, height) = image.size
            size = (800, 800)
            "Max width and height 800"
            if width > 800:
                image.thumbnail(size, Image.ANTIALIAS)
                image.save(self.image.path, "PNG")

    postsection = models.ForeignKey(
        to=PostSection,
        verbose_name=u'Категория',
        blank=True,
        null=True
    )
    image = models.ImageField(
        verbose_name=u'Изображения',
        upload_to=upload_to,
        blank=True,
        null=True
    )
    video = models.TextField(
        verbose_name=u'HTML код видео',
        blank=True,
        null=True
    )
    description = RichTextField(
        verbose_name=u'Описание'
    )
    slug = models.SlugField(
        max_length=100,
        verbose_name=u'url'
    )
    sort = models.PositiveIntegerField(default=1, verbose_name=u'Сортировка')
    send = models.BooleanField(default=False)


class PostComment(Common):
    class Meta:
        verbose_name = u'Комментарий'
        verbose_name_plural = u'Комментарии'
        app_label = 'blog'
        ordering = ('-created',)

    def __unicode__(self):
        return u'Комментарий %s от %s' % (self.name, self.created)

    post = models.ForeignKey(to=Post, verbose_name=u'Статья', null=True, blank=True)
    name = models.CharField(
        verbose_name=u'Ваше имя',
        max_length=256
    )
    mail = models.EmailField(
        verbose_name=u'Ваш email',
        max_length=100
    )
    text = models.TextField(
        verbose_name=u'Сообщение'
    )

apps/blog/forms.py
# coding=utf-8
from django import forms
from .models import PostComment

__author__ = 'alexy'


class PostCommentForm(forms.ModelForm):
    class Meta:
        model = PostComment
        fields = '__all__'

apps/blog/views.py
# coding=utf-8
from annoying.functions import get_object_or_None
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from .models import PostSection, Post, PostComment, BlogSetup

__author__ = 'alexy'


class PostListView(ListView):
    model = Post
    template_name = 'blog/post_list.html'

    def get_queryset(self):
        qs = Post.objects.all()[0:3]
        return qs

    def get_context_data(self, **kwargs):
        context = super(PostListView, self).get_context_data()
        try:
            setup = BlogSetup.objects.first()
            context.update({
                'META_TITLE': setup.meta_title,
                'META_KEY': setup.meta_key,
                'META_DESC': setup.meta_desc,
            })
        except:
            pass
        return context


class PostDetailView(DetailView):
    model = Post
    template_name = 'blog/post_detail.html'

    def get_context_data(self, **kwargs):
        context = super(PostDetailView, self).get_context_data()
        if self.object.meta_title:
            meta_title = self.object.meta_title
        else:
            meta_title = self.object.title
        meta_key = self.object.meta_key
        meta_desc = self.object.meta_desc
        context.update({
            'META_TITLE': meta_title,
            'META_KEY': meta_key,
            'META_DESC': meta_desc
        })
        return context


class PostSectionDetailView(DetailView):
    model = PostSection
    template_name = 'blog/post_list.html'

    def get_context_data(self, **kwargs):
        context = super(PostSectionDetailView, self).get_context_data()
        if self.object.meta_title:
            meta_title = self.object.meta_title
        else:
            meta_title = self.object.title
        meta_key = self.object.meta_key
        meta_desc = self.object.meta_desc
        context.update({
            'META_TITLE': meta_title,
            'META_KEY': meta_key,
            'META_DESC': meta_desc
        })
        return context

apps/blog/templates/blog/blog_base.html
<!DOCTYPE html>
<html lang="ru">
<head>
	<meta charset="utf-8">
  <title>{{ META_TITLE|default:'Не указано' }}</title>
  <meta name="keywords" content="{{ META_KEY|safe|default:'' }}">
  <meta name="description" content="{{ META_DESC|safe|default:'' }}">
	<meta name="format-detection" content="telephone=no">
  {% load staticfiles %}
	<link href="{% static 'blog/favicon.ico' %}" rel="shortcut icon" type="image/x-icon" />

	<link media="all" rel="stylesheet" type="text/css" href="{% static 'blog/css/all.min.css' %}" />
	<link media="all" rel="stylesheet" type="text/css" href="{% static 'blog/css/nivo-slider.min.css' %}" />
	<link media="all" rel="stylesheet" type="text/css" href="{% static 'blog/css/jquery.fancybox.min.css' %}" />
	<!--[if lt IE 9]><script type="text/javascript" src="{% static 'blog/js/html5.js' %}"></script><![endif]-->
	<!--[if lt IE 9]><script type="text/javascript" src="{% static 'blog/js/placeholder.js' %}"></script><![endif]-->

  {{ SETUP.top_js|safe|default:'' }}
</head>
<body>
	<div id="wrapper">
		<header class="header">
			<div class="city-hidden city1">
				<div class="holder">
					<a href="" class="city-close">x</a>
					<div class="city-block">
          {% if CITY_LIST %}
						<ul class="city-list">
            {% for city in CITY_LIST %}
              <li>{{ city.name }}</li>
            {% endfor %}
						</ul>
          {% endif %}
					</div>
				</div>
			</div>
			<div class="header-top">	
				<div class="holder">
						<div class="slogan">
						<span class="orange">Бизнес</span>, с которым<br> 
						<span class="orange">справится</span> даже <span class="green">1</span> человек
					</div>

					<div class="logo">
						<img src="{% static 'blog/images/logo.png' %}" alt="">
					</div>
					<div class="header-right">
						<div class="header-city-link"><a href="">Города присутствия</a></div>
						<div class="header-phone">{{ SETUP.phone|default:'0 000 000 000 00' }}</div>
					</div>
				</div>
			</div>
			<div class="header-fix header-fix-top">
				<div class="header-fix-holder">
					<div class="holder">
						<a href="{% url 'landing:index' %}" class="back">Вернуться на Главную</a>
						<a href="{% url 'blog:list' %}" class="back-blog" >Список статей</a>
						<div class="search">
							<form action="">
								<fieldset>
									<input type="text" class="search-input" placeholder="Поиск по сайту">
									<button class="search-loupe"></button>
								</fieldset>
							</form>
						</div>
					</div>
				</div>
			</div>
		</header>	
		<section class="blog">
			<div class="holder">
				{% include 'blog/__includes/blog_sidebar.html' %}
				<section class="content">

{% block content %}
{% endblock %}

				</section>
			</div>	
		</section>
		<section class="ask">
			<div class="holder">
				<div class="form-block">
					<div class="form-title">Остались вопросы? </div>
					<div class="form-text">Задайте ваш вопрос в форме ниже</div>
					<form action="{% url 'ticket:send' %}" method="post">{% csrf_token %}
						<fieldset>
							<div class="input-block">
								<input type="text" name="name" class="input" placeholder="Ваше имя *">
								<input type="text" name="phone" class="input no-margin" placeholder="+7 (___) ___ - __ - __">
							</div>
							<div class="textarea-block">
								<textarea name="comment" cols="30" rows="10" class="textarea" placeholder="Ваш вопрос *"></textarea>
							</div>
							<input type="hidden" name="theme" value="1">
							<div class="submit-holder">
								<button class="submit">Получить консультацию</button>
							</div>
						</fieldset>
            <fieldset class="terms text-center">
              <input type="checkbox" name="terms" id="id-terms">
              <label for="id-terms">Я согласен на <a href="{% url 'landing:personal' %}" target="_blank">обработку персональной информации</a></label>
            </fieldset>
					</form>
					<div class="form-text-min">Мы гарантируем конфиденциальность</div>
				</div>
			</div>
		</section>
		
		<footer class="footer">
			<div class="holder">
				<div class="footer-logo"><img src="{% static 'blog/images/logo.png' %}" alt=""></div>
				<div class="copy"><a href="#hidden-block" class="fancybox">Политика конфиденциальности</a><br>
				РА «Дружба» &copy; 2015</div>
				<a href="http://5lands.ru/" target="_blank" class="studio">
					Дизайн сайта<br>
					<img src="{% static 'blog/images/studio.png' %}" alt="">
				</a>
				<div class="footer-phone">{{ SETUP.phone|default:'0 000 000 000 00' }}</div>
				<div id="hidden-block">
					<h2>Политика конфиденциальности</h2>
					<p>Мы не собираем личную информацию о Вас, когда Вы заходите на наш сайт. 
					Вы можете анонимно просматривать сайт. Тем не менее, Ваш браузер все же автоматически сообщает нам тип компьютера и операционной системы, которые Вы используете. Единственная личная информация о Вас, которую мы получаем, это те данные, которые Вы добровольно предоставляете при заполнении форм.
					При заполнении форм на сайте у Вас запросят персональную информацию, такую как имя, номер телефона. Предоставление такой информации в ответ на запрос осуществляется Вами исключительно добровольно. 
					Предоставленная Вами информация используется чтобы оказать те услуги, которые Вы сами запрашиваете.
					</p>
				</div>
			</div>	
		</footer>	
		<!--   Всплывающие окна  -->
		<div id="popup">	
			<div class="video-popup">
				<iframe width="800" height="600" src="https://www.youtube.com/embed/Y1wWqG4UiTY" frameborder="0" allowfullscreen></iframe>
			</div>
		</div>
		<div id="boxes">
			<div id="dialog" class="window">
				<div class="tablet-popup">
					<div class="tablet-video">
						<iframe width="695" height="522" src="https://www.youtube.com/embed/Y1wWqG4UiTY" frameborder="0" allowfullscreen></iframe>
					</div>
				</div>
			</div>
			<div id="mask"></div>
		</div>
		<!--   Всплывающие окна end  -->
	</div>
<script src="{% static 'blog/js/jquery-1.9.1.min.js' %}"></script>
<script src="{% static 'blog/js/jquery.nivo.slider.pack.js' %}"></script>
<script src="{% static 'blog/js/jquery.validate.js' %}"></script>
<script src="{% static 'blog/js/jquery.form.js' %}"></script>
<script src="{% static 'blog/js/notify-combined.min.js' %}"></script>
<script src="{% static 'blog/js/jquery.fancybox.js' %}"></script>
<script src="{% static 'blog/js/tabs.js' %}"></script>
<script src="{% static 'blog/js/jquery.scrollTo.js' %}"></script>
<script src="{% static 'blog/js/jquery.maskedinput.js' %}"></script>
<script src="{% static 'blog/js/all.js' %}"></script>
{{ SETUP.bottom_js|safe|default:'' }}
</body>
</html>

apps/blog/templates/blog/ok.html
<!DOCTYPE html>
<html lang="ru">
<head>
	<meta charset="utf-8">
	<meta name="keywords" content="">
	<meta name="description" content="">
	<meta name="format-detection" content="telephone=no">
	<link href="favicon.ico" rel="shortcut icon" type="image/x-icon" />
	<title>Рекламное агентство Дружба</title>
	<link media="all" rel="stylesheet" type="text/css" href="css/all.css" />
	<link media="all" rel="stylesheet" type="text/css" href="css/jquery.fancybox.css" />
	<script src="js/jquery-1.9.1.min.js"></script>
	<script src="js/jquery.validate.js"></script>
	<script src="js/jquery.fancybox.js"></script>
	<script src="js/tabs.js"></script>
	<script src="js/jquery.scrollTo.js"></script>
	<script src="js/jquery.maskedinput.js"></script>
	<!--[if lt IE 9]><script type="text/javascript" src="js/html5.js"></script><![endif]-->
	<!--[if lt IE 9]><script type="text/javascript" src="js/placeholder.js"></script><![endif]-->
	<script src="js/all.js"></script>
	<script type="text/javascript">
		setTimeout('location.replace("index.html")', 3000);
	</script>
</head>
<body>
	<div id="wrapper" class="thnx">
		<div class="thnx-text">
			СПАСИБО ЗА ВАШУ ЗАЯВКУ<br> МЫ СВЯЖЕМСЯ С ВАМИ<br> ЧЕРЕЗ НЕСКОЛЬКО МИНУТ
		</div>	
	</div>
</body>
</html>

apps/blog/templates/blog/post_detail.html
{% extends 'blog/blog_base.html' %}
{% block content %}
  {% load staticfiles %}
					<article class="blog-article">
						<h1>{{ object.title|default:'Заголовок статьи' }}</h1>
						<div class="blog-line">
							<span class="blog-date">{{ object.created|default:'' }}</span>
							<a href="#comment" class="blog-comment-link">комментариев: {{ object.postcomment_set.count|default:'0' }}</a>
						</div>
            {% if object.image %}
						<a href="{{ object.image.url }}" class="blog-img fancybox"><img src="{{ object.image.url }}" alt=""></a>
            {% endif %}
            {% if object.video %}
              {{ object.video|safe }}
            {% endif %}
						{{ object.description|safe|default:'' }}
					</article>
					<div class="blog-webs">
            {% if object.get_previous_by_created %}
						<a href="{{ object.get_previous_by_created.get_absolute_url }}" class="blog-prev">Назад</a>
            {% endif %}
            {% if object.get_next_by_created %}
						<a href="{{ object.get_next_by_created.get_absolute_url }}" class="blog-next">Вперед</a>
            {% endif %}
						<div class="webs">
							<img src="{% static 'blog/images/webs.jpg' %}" alt="" >
						</div>
					</div>
					<div class="comment-block" id="comment">
						<ul class="comment-list">
            {% for comment in object.postcomment_set.all %}
							<li class="comment-item">
								<div class="comment-top">
									<div class="comment-login"><a href="">{{ comment.name|default:'anonymous' }}</a></div>
									<div class="comment-time">{{ comment.created|default:'' }}</div>
								</div>
								<div class="comment-text">
									{{ comment.text|safe|default:'' }}
								</div>
							</li>
            {% empty %}
              <li class="comment-item">
                <p class="empty">Нет комментариев</p>
              </li>
            {% endfor %}
						</ul>
						<div class="comment-form">
							<form action="{% url 'blog:postcomment-add' %}" method="post">{% csrf_token %}
								<fieldset>
                  <input type="hidden" name="post" value="{{ object.id|default:'' }}">
									<input name="name" type="text" class="input" placeholder="Ваш имя *">
									<input name="mail" type="text" class="input" placeholder="Ваш e-mail *">
									<textarea name="text" cols="30" rows="10" class="textarea required" placeholder="Сообщение"></textarea>
									<button class="submit submit-green">Оставить комментарий</button>
								</fieldset>
							</form>
						</div>
						<a href="" class="comment-button submit submit-green">Оставить комментарий</a>
					</div>
{% endblock %}

apps/blog/templates/blog/post_detail_mail.html
<html>
<body>
  <a href="http://лидерфраншиз.рф{{ object.get_absolute_url }}">Посмотреть статью на сайте</a>
  <article class="blog-article">
    <h1>{{ object.title|default:'Заголовок статьи' }}</h1>
    <div class="blog-line">
      <span class="blog-date">{{ object.created|default:'' }}</span>
    </div>
    {% if object.image %}
    <img src="http://лидерфраншиз.рф{{ object.image.url }}" alt="">
    {% endif %}
    {% if object.video %}
      {{ object.video|safe }}
    {% endif %}
    {{ object.description|safe|default:'' }}
  </article>
</body>
</html>

apps/blog/templates/blog/post_list.html
{% extends 'blog/blog_base.html' %}
{% block content %}
{% load staticfiles %}
          <div class="blog-list">
          {% if object_list %}
            {% for post in object_list %}
            <div class="blog-item">
              {% if post.image %}
              <a href="{% url 'blog:detail' post.slug %}" class="blog-img"><img src="{{ post.image.url }}" alt="{{ post.title|default:'' }}"></a>
              {% endif %}
              {% if post.video %}
              {{ post.video|safe }}
              {% endif %}
              <h3>{{ post.title|default:'' }}</h3>
              <div class="blog-line">
                <span class="blog-date">{{ post.created }}</span>
                <a href="{% url 'blog:detail' post.slug %}#comment" class="blog-comment-link">комментариев: {{ post.postcomment_set.count|default:'0' }}</a>
              </div>
              <div class="blog-text">{{ post.description|striptags|safe|truncatewords:50 }}</div>
              <div class="blog-button"><a href="{% url 'blog:detail' post.slug %}" class="submit">Читать далее</a></div>
            </div>
            {% empty %}
            <div class="blog-item">
              <h3>Статей не найдено</h3>
            </div>
            {% endfor %}
          {% endif %}
          {% if object %}
            {% for post in object.post_set.all %}
            <div class="blog-item">
              {% if post.image %}
              <a href="{% url 'blog:detail' post.slug %}" class="blog-img"><img src="{{ post.image.url }}" alt="{{ post.title|default:'' }}"></a>
              {% endif %}
              {% if post.video %}
              {{ post.video|safe }}
              {% endif %}
              <h3>{{ post.title|default:'' }}</h3>
              <div class="blog-line">
                <span class="blog-date">{{ post.created }}</span>
                <a href="{% url 'blog:detail' post.slug %}#comment" class="blog-comment-link">комментариев: {{ post.postcomment_set.count|default:'0' }}</a>
              </div>
              <div class="blog-text">{{ post.description|striptags|safe|truncatewords:50 }}</div>
              <div class="blog-button"><a href="{% url 'blog:detail' post.slug %}" class="submit">Читать далее</a></div>
            </div>
            {% empty %}
            <div class="blog-item">
              <h3>Статей не найдено</h3>
            </div>
            {% endfor %}
          {% endif %}
            <button class="more-button" data-count="3" data-section="{% if object %}{{ object.id }}{% endif %}" data-ajax-url="{% url 'blog:load-more' %}" id="js-button-show-more-post"><img src="{% static 'blog/images/round-arrow.png' %}" alt="" class="arrow-icon">Показать ещё публикации</button>
          </div>
{% endblock %}